# Generated by Django 5.0.6 on 2024-06-01 13:12

import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone Number')),
                ('shop_name', models.CharField(max_length=50, unique=True, verbose_name='Shop Name')),
                ('shop_url', models.URLField(unique=True, verbose_name='Shop URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner')),
                ('street1', models.CharField(max_length=50, verbose_name='Street 1')),
                ('street2', models.CharField(blank=True, max_length=50, verbose_name='Street 2')),
                ('city', models.CharField(max_length=100, verbose_name='Town / City')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='State')),
                ('password', models.CharField(verbose_name='Password')),
                ('confirm_password', models.CharField(verbose_name='Confirm Password')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is the shop visible in the shops catalog')),
            ],
            options={
                'verbose_name': 'Խանութ',
                'verbose_name_plural': 'Խանութներ',
            },
        ),
    ]
